### ISSUE TITLE
please give source code

### ISSUE THREAD

**Issue by ethaniccc** [WeatherClient/WeatherClient#5]
omg bro pls give source coed i like jack off 24/7 dereaming oefff tehhhe dxay i get sourde code pslsss my pp is begging

**Comment by hrkyr** [comment]
are u gonna patch the stuff in ur sh1t anticheat (it is good u are just a anticheat maker so i be mean)?

**Comment by ethaniccc** [comment]
Gibe Weather source for anticheet source no cap

**Comment by hrkyr** [comment]
ethan thicc ngl estoric on top

**Comment by shape1234** [comment]
i don't like anticheats

**Comment by ethaniccc** [comment]
pen sive
